
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'statementARROW BOOL COLON ELSE EQ EQEQ FUN GT ID IF LET LPAREN LT MINUS NUMBER PLUS RPAREN SEMI THEN TIMES TYPEexpr : expr PLUS expr\n| expr MINUS expr\n| expr TIMES exprexpr : expr LT expr\n| expr GT expr\n| expr EQEQ exprexpr : LPAREN expr RPARENexpr : NUMBERexpr : BOOLexpr : IDexpr : MINUS NUMBERexpr : ID LPAREN expr RPARENstatement : LET ID EQ expr SEMIstatement : FUN ID COLON TYPE ARROW TYPE SEMIstatement : LET ID ID EQ expr SEMIexpr : IF expr THEN expr ELSE exprstatement : expr SEMI'
    
_lr_action_items = {'LET':([0,],[2,]),'FUN':([0,],[5,]),'LPAREN':([0,3,7,10,12,14,15,16,17,18,19,25,35,36,44,],[7,12,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'NUMBER':([0,6,7,10,12,14,15,16,17,18,19,25,35,36,44,],[8,21,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'BOOL':([0,7,10,12,14,15,16,17,18,19,25,35,36,44,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'ID':([0,2,5,7,10,11,12,14,15,16,17,18,19,25,35,36,44,],[3,11,20,3,3,24,3,3,3,3,3,3,3,3,3,3,3,]),'MINUS':([0,3,4,7,8,9,10,12,14,15,16,17,18,19,21,22,23,25,26,27,28,29,30,31,32,34,35,36,37,38,40,41,44,47,],[6,-10,15,6,-8,-9,6,6,6,6,6,6,6,6,-11,15,15,6,15,15,15,15,15,15,15,-7,6,6,15,-12,15,15,6,15,]),'IF':([0,7,10,12,14,15,16,17,18,19,25,35,36,44,],[10,10,10,10,10,10,10,10,10,10,10,10,10,10,]),'$end':([1,13,42,45,48,],[0,-17,-13,-15,-14,]),'SEMI':([3,4,8,9,21,27,28,29,30,31,32,34,37,38,41,46,47,],[-10,13,-8,-9,-11,-1,-2,-3,-4,-5,-6,-7,42,-12,45,48,-16,]),'PLUS':([3,4,8,9,21,22,23,26,27,28,29,30,31,32,34,37,38,40,41,47,],[-10,14,-8,-9,-11,14,14,14,14,14,14,14,14,14,-7,14,-12,14,14,14,]),'TIMES':([3,4,8,9,21,22,23,26,27,28,29,30,31,32,34,37,38,40,41,47,],[-10,16,-8,-9,-11,16,16,16,16,16,16,16,16,16,-7,16,-12,16,16,16,]),'LT':([3,4,8,9,21,22,23,26,27,28,29,30,31,32,34,37,38,40,41,47,],[-10,17,-8,-9,-11,17,17,17,17,17,17,17,17,17,-7,17,-12,17,17,17,]),'GT':([3,4,8,9,21,22,23,26,27,28,29,30,31,32,34,37,38,40,41,47,],[-10,18,-8,-9,-11,18,18,18,18,18,18,18,18,18,-7,18,-12,18,18,18,]),'EQEQ':([3,4,8,9,21,22,23,26,27,28,29,30,31,32,34,37,38,40,41,47,],[-10,19,-8,-9,-11,19,19,19,19,19,19,19,19,19,-7,19,-12,19,19,19,]),'RPAREN':([3,8,9,21,22,26,27,28,29,30,31,32,34,38,47,],[-10,-8,-9,-11,34,38,-1,-2,-3,-4,-5,-6,-7,-12,-16,]),'THEN':([3,8,9,21,23,27,28,29,30,31,32,34,38,47,],[-10,-8,-9,-11,35,-1,-2,-3,-4,-5,-6,-7,-12,-16,]),'ELSE':([3,8,9,21,27,28,29,30,31,32,34,38,40,47,],[-10,-8,-9,-11,-1,-2,-3,-4,-5,-6,-7,-12,44,-16,]),'EQ':([11,24,],[25,36,]),'COLON':([20,],[33,]),'TYPE':([33,43,],[39,46,]),'ARROW':([39,],[43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expr':([0,7,10,12,14,15,16,17,18,19,25,35,36,44,],[4,22,23,26,27,28,29,30,31,32,37,40,41,47,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_bin','parser.py',12),
  ('expr -> expr MINUS expr','expr',3,'p_expr_bin','parser.py',13),
  ('expr -> expr TIMES expr','expr',3,'p_expr_bin','parser.py',14),
  ('expr -> expr LT expr','expr',3,'p_expr_cmp','parser.py',18),
  ('expr -> expr GT expr','expr',3,'p_expr_cmp','parser.py',19),
  ('expr -> expr EQEQ expr','expr',3,'p_expr_cmp','parser.py',20),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','parser.py',24),
  ('expr -> NUMBER','expr',1,'p_expr_num','parser.py',28),
  ('expr -> BOOL','expr',1,'p_expr_bool','parser.py',32),
  ('expr -> ID','expr',1,'p_expr_id','parser.py',36),
  ('expr -> MINUS NUMBER','expr',2,'p_expr_neg','parser.py',40),
  ('expr -> ID LPAREN expr RPAREN','expr',4,'p_expr_call','parser.py',46),
  ('statement -> LET ID EQ expr SEMI','statement',5,'p_let_var','parser.py',60),
  ('statement -> FUN ID COLON TYPE ARROW TYPE SEMI','statement',7,'p_fun_signature','parser.py',67),
  ('statement -> LET ID ID EQ expr SEMI','statement',6,'p_fun_def','parser.py',73),
  ('expr -> IF expr THEN expr ELSE expr','expr',6,'p_if','parser.py',80),
  ('statement -> expr SEMI','statement',2,'p_statement_expr','parser.py',86),
]
